baseurl = "https://NoPosh.github.io/forestranger/"
title = "Forest Ranger"
theme = "hugo-profile"
locale = "ru-ru"

[params]
	# Основные настройки
	description = "Разработка мобильной игры Forest Ranger на Unity"
	animate = true

	[params.terms]
        toc = "Содержание"
        read = "Читать"
        copyright = "Все права защищены"
        emailText = "Посмотрите этот проект"

	#Настройка главного экрана
	[params.hero]
	 enable = true
	 title = "Forest Ranger"
	 subtitle = "Мобильная игра про егеря в лесу"
	 content = "Сайт-отчет по проектной практике"
	 image = "img/hero.png"	#TODO: положить скриншот игры сюда


	 # Кнопка на главном экране
		[params.hero.button]
            enable = true
            name = "Подробнее"
            url = "/forestranger/about"

	[params.singlePages]
        socialShare = false # Выключает плашку Socials
        [params.singlePages.scrollprogress] # Красивая полоска прогресса чтения сверху
            enable = true
        [params.singlePages.readTime]
            enable = true
            content = "мин. чтения"

    [params.navbar]
        disableSearch = true
        brandName = "Forest Ranger"
        brandLogo = "img/logo.png"     #Сюда бы небольшое лого
        showBrandLogo = true


	[[params.social]]
        icon = "fab fa-github"
        url = "https://github.com/NoPosh/ForestRangerGame"

# Настройка меню
[[menu.main]]
 name = "О проекте"
 url = "/about"
 weight = 1

[[menu.main]]
 name = "Участники"
 url = "/members"
 weight = 2

[[menu.main]]
 name = "Журнал"
 url = "/posts"
 weight = 3

[[menu.main]]
 name = "Ресурсы"
 url = "/resources"
 weight = 4

 [languages]
  [languages.ru]
  languageName = "Russian"
  title = "Forest Ranger"
  contentDir = "content"
  weight = 1

  [markup]
    [markup.goldmark.renderer]
        unsafe = true # Чтобы работали картинки и HTML в Markdown